In [4]:
import pandas as pd
import numpy as np

In [2]:
path = '../test_sal/interval_tests/data/'

In [16]:
dic = {}
for i in range(4):
    dic[f'data{i}'] = pd.read_csv(f'{path}ionlist{i}data_.csv', delim_whitespace=True)

In [19]:
type(dic['data0'])

pandas.core.frame.DataFrame

In [20]:
dic['data0']

,name,wave,redshift,col_dens,delta_v,vel_dispersion,interval_start,interval_end,density,temperature,metallicity,lightray_index
0,O VI,1031.912,0.0,13.105821,6.411014,2.288635,201,212.0,6.332234e-29,143180.658835,1.066194,0.0
1,O VI,1031.912,0.0,12.957485,-14.711344,7.669175,227,233.0,6.943463e-29,122109.873055,1.078423,0.0
2,O VI,1031.912,0.0,13.240453,65.442516,4.888650,239,257.0,5.156165e-29,153264.768084,1.094867,36.0
3,O VI,1031.912,0.0,12.814330,49.937354,4.247963,257,268.0,9.119172e-29,114519.356300,1.076106,36.0
4,O VI,1031.912,0.0,13.039680,25.781228,7.560109,268,278.0,4.721361e-29,139632.194417,1.024358,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...
221,N I,1200.223,0.0,16.995223,49.805857,2.061932,292,305.0,8.838736e-24,907.815825,1.102594,46.0
222,N I,1200.223,0.0,14.843616,52.446161,1.099674,120,138.0,1.860030e-26,12579.829999,1.080756,16.0
223,N I,1200.223,0.0,13.039855,60.861225,1.614533,106,115.0,4.598925e-27,19766.243532,1.103243,30.0
224,N I,1200.223,0.0,17.000839,146.304843,1.897163,231,240.0,1.527429e-23,546.926134,1.069092,22.0
225,N I,1200.223,0.0,14.855585,-121.340504,8.537891,114,155.0,1.509395e-26,13274.682730,1.079608,4.0

In [22]:
dic['data1']

,name,wave,redshift,col_dens,delta_v,vel_dispersion,interval_start,interval_end,density,temperature,metallicity,lightray_index
0,O VI,1031.912,0.0,13.105821,6.411014,2.288635,201,212.0,6.332234e-29,143180.658835,1.066194,0.0
1,O VI,1031.912,0.0,12.957485,-14.711344,7.669175,227,233.0,6.943463e-29,122109.873055,1.078423,0.0
2,O VI,1031.912,0.0,13.240453,65.442516,4.888650,239,257.0,5.156165e-29,153264.768084,1.094867,36.0
3,O VI,1031.912,0.0,12.814330,49.937354,4.247963,257,268.0,9.119172e-29,114519.356300,1.076106,36.0
4,O VI,1031.912,0.0,13.039680,25.781228,7.560109,268,278.0,4.721361e-29,139632.194417,1.024358,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...
208,N I,1200.223,0.0,16.995223,49.805857,2.061932,292,305.0,8.838736e-24,907.815825,1.102594,46.0
209,N I,1200.223,0.0,14.843616,52.446161,1.099674,120,138.0,1.860030e-26,12579.829999,1.080756,16.0
210,N I,1200.223,0.0,13.039855,60.861225,1.614533,106,115.0,4.598925e-27,19766.243532,1.103243,30.0
211,N I,1200.223,0.0,17.000839,146.304843,1.897163,231,240.0,1.527429e-23,546.926134,1.069092,22.0
212,N I,1200.223,0.0,14.855585,-121.340504,8.537891,114,155.0,1.509395e-26,13274.682730,1.079608,4.0

In [23]:
dic['data2']

,name,wave,redshift,col_dens,delta_v,vel_dispersion,interval_start,interval_end,density,temperature,metallicity,lightray_index
0,O VI,1031.912,0.0,13.105821,6.411014,2.288635,201,212.0,6.332234e-29,143180.658835,1.066194,0.0
1,O VI,1031.912,0.0,12.957485,-14.711344,7.669175,227,233.0,6.943463e-29,122109.873055,1.078423,0.0
2,O VI,1031.912,0.0,13.240453,65.442516,4.888650,239,257.0,5.156165e-29,153264.768084,1.094867,36.0
3,O VI,1031.912,0.0,12.814330,49.937354,4.247963,257,268.0,9.119172e-29,114519.356300,1.076106,36.0
4,O VI,1031.912,0.0,13.039680,25.781228,7.560109,268,278.0,4.721361e-29,139632.194417,1.024358,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...
218,N I,1200.223,0.0,16.995223,49.805857,2.061932,292,305.0,8.838736e-24,907.815825,1.102594,46.0
219,N I,1200.223,0.0,14.843616,52.446161,1.099674,120,138.0,1.860030e-26,12579.829999,1.080756,16.0
220,N I,1200.223,0.0,13.039855,60.861225,1.614533,106,115.0,4.598925e-27,19766.243532,1.103243,30.0
221,N I,1200.223,0.0,17.000839,146.304843,1.897163,231,240.0,1.527429e-23,546.926134,1.069092,22.0
222,N I,1200.223,0.0,14.855585,-121.340504,8.537891,114,155.0,1.509395e-26,13274.682730,1.079608,4.0

In [24]:
dic['data3']

,name,wave,redshift,col_dens,delta_v,vel_dispersion,interval_start,interval_end,density,temperature,metallicity,lightray_index
0,O VI,1031.912,0.0,13.105821,6.411014,2.288635,201,212.0,6.332234e-29,143180.658835,1.066194,0.0
1,O VI,1031.912,0.0,12.957485,-14.711344,7.669175,227,233.0,6.943463e-29,122109.873055,1.078423,0.0
2,O VI,1031.912,0.0,13.240453,65.442516,4.888650,239,257.0,5.156165e-29,153264.768084,1.094867,36.0
3,O VI,1031.912,0.0,12.814330,49.937354,4.247963,257,268.0,9.119172e-29,114519.356300,1.076106,36.0
4,O VI,1031.912,0.0,13.039680,25.781228,7.560109,268,278.0,4.721361e-29,139632.194417,1.024358,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...
231,N I,1200.223,0.0,16.995223,49.805857,2.061932,292,305.0,8.838736e-24,907.815825,1.102594,46.0
232,N I,1200.223,0.0,14.843616,52.446161,1.099674,120,138.0,1.860030e-26,12579.829999,1.080756,16.0
233,N I,1200.223,0.0,13.039855,60.861225,1.614533,106,115.0,4.598925e-27,19766.243532,1.103243,30.0
234,N I,1200.223,0.0,17.000839,146.304843,1.897163,231,240.0,1.527429e-23,546.926134,1.069092,22.0
235,N I,1200.223,0.0,14.855585,-121.340504,8.537891,114,155.0,1.509395e-26,13274.682730,1.079608,4.0

In [33]:
rays = {}
for ds in dic:
    for index in range(len(ds['name'])):
        

data = {}
for i in range(4):
    data[f'dataset{i}'] = {}
for ds in data:
    data[ds] = {''}

{}
{}
{}
{}

In [48]:
dic.keys()

dict_keys(['data0', 'data1', 'data2', 'data3'])

In [40]:
bruh = {'data0': {}, 'data1': {}, 'data2':{}, 'data3': {}}
for ds in dic:
    bruh[ds]['bro'] = 2
bruh

{'data0': {'bro': 2},
 'data1': {'bro': 2},
 'data2': {'bro': 2},
 'data3': {'bro': 2}}

In [53]:
dick = dict(a=[1,2], b=[3,4], c=[5,6])
ddick = dict(a=[1,2], b=[3,4], c=[5,6])
# print(f'dick before: {dick}')
# dick['a'] += 1
# print(f'dick now: {dick}')

Dick = pd.DataFrame(dick)
Ddick = pd.DataFrame(ddick)

print(Dick)
print(Ddick)

for index in range(len(Dick['a'])):
    if Dick['a'][index] == Ddick['a'][index]:
        print('yuh')

   a  b  c
0  1  3  5
1  2  4  6
   a  b  c
0  1  3  5
1  2  4  6
yuh
yuh

In [54]:
len(dick['a'])

2

In [36]:
#dic['data0']['name']
# ion_list = []
# STILL NEED TO ADD RAYS AND NUMBER OF RAYS
kwargs = dict(delim_whitespace=True)
def check_abs_differences(filename_list, **kwargs):
    
    dic = {}
    for i in range(len(filename_list)):
        
        dic[f'data{i}'] = pd.read_csv(filename_list[i], **kwargs)
    
    def find_abs_differences(dic, record_index):
        data = {}

        for i in range(len(dic.keys())):
            data[f'data{i}'] = {}

        for ds in dic:

            for index in range(len(ds['name'])):

                if index == 0:
                    #ion_list.append(ds['name'][index])
                    data[ds][f'{ds['name'][index]}'] = {}
                    #rays[f'{ds['lightray_index'][index]}'] = 1
                    data[ds][f'{ds['name'][index]}'][f'{ds['lightray_index'][index]}'] = 1
                else:

                    if ds['name'][index] == ds['name'][index-1]:

                        if ds['lightray_index'][index] == ds['lightray_index'][index-1]:
                            #rays[f'{ds['lightray_index'][index]}'] += 1
                            data[ds][f'{ds['name'][index]}'][f'{ds['lightray_index'][index]}'] += 1
                        else:
                            data[ds][f'{ds['name'][index]}'][f'{ds['lightray_index'][index]}'] = 1

                    else:
                        data[ds][f'{ds['name'][index]}'] = {}
                        data[ds][f'{ds['name'][index]}'][f'{ds['lightray_index'][index]}'] = 1
        master_dic = {}
        
        for dataset in dic:
            master_dic[f'{dataset}'] = _check_absorber_interval(dataset, check_num=3)
        
        return master_dic
            
    
    record_index = {}
    for i in range(len(dic.keys())):
                record_index[f'data_index_record{i}'] = []
            
    for dataset in range(len(dic.keys())):
        if dataset == 0:
            pass
        else:
            for index in range(len(dic[f'data{dataset}'])):
                if dic[f'data{dataset}'][index] == dic[f'data{dataset-1}'][index]:
                    pass
                else:
                    record_index[f'data_index_record{dataset}'].append(index)
                    
    for i in range(len(dic.keys())):
        if len(record_index[f'data_index_record{i}']) == 0:
            print(f'dataset {i} is in the clear!')
        else:
            find_abs_differences(dic, record_index)

0      O VI
1      O VI
2      O VI
3      O VI
4      O VI
       ...
221     N I
222     N I
223     N I
224     N I
225     N I
Name: name, Length: 226, dtype: object

In [ ]:
"""
data = {'dataset0': {'ion': {'ray': num_rays}}, 'dataset1': {'ion': {'ray': num_rays}}....dataset3}



for ds in range(len(data.keys())-1):
    for ion_key in data[f'dataset{ds}'].keys():
        for ray_key in data[f'dataset{ds}'][ion_key].keys():
            
            if data[f'dataset{ds}'][ion_key][ray_key] != data[f'dataset{ds+1}'][ion_key][ray_key]:
                print(f"DATASETS: {ds}, {ds+1}; ION: {ion_key}; RAY INDEX: {ray_key}; NUM: {data[f'dataset{ds}'][ion_key][ray_key]}, {data[f'dataset{ds+1}'][ion_key][ray_key]}")
"""

In [25]:
d = {'a': {'A': {'apple': 'banana'}}, 'b': {'B': {'bonk': 'cat'}}}

In [28]:
d['a']['A']['apple']

'banana'

In [30]:
for i in d.keys():
    print(d[i])

{'A': {'apple': 'banana'}}
{'B': {'bonk': 'cat'}}